//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cars
    {
        public int id { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<bool> is_new { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        public virtual tbl_users tbl_users { get; set; }
    }
}
